KBD Component
iTwin/stratakit pull request #139
Opened 2024-11-13 13:29 UTC by RichardHill

**Summary**

This PR introduces the Kbd component to the KIWI Component Library, providing a consistent and accessible way to display keyboard input instructions. The Kbd component improves readability and aligns with accessibility standards, ensuring users can easily identify keyboard commands across the application. 

**Changes**

The Kbd component is implemented with a focus on accessibility and customization. Key aspects of the component’s functionality are as follows:

Semantic Markup: Uses the `<kbd>` HTML tag to semantically indicate keyboard input, which is widely recognized by screen readers.

Styling: Applies styles to make keyboard shortcuts visually distinct, as dictated by the design

Tests :

AXE Tests, Visual Tests and some elementary tests have been added.

Note: 

Although `<kbd>` is a semantic HTML element, it currently lacks a mapped ARIA role and is not broadly recognised by screen readers. Nonetheless, we use the `<kbd>` element because semantic HTML has value beyond accessibility alone. In the future, if the `<kbd>` element gains an implied ARIA role, our implementation will automatically take advantage of this.

2024-11-20 16:55 UTC, knowler requested changes
I didn’t do a thorough review, but if we can start with the concerns I’ve raised, I can circle back and continue.

2024-11-20 16:55 UTC, knowler commented on apps/test-app/app/routes/tests/kbd/index.tsx
> +		</>
We don’t need the fragment.
```suggestion
		<Kbd data-testid="kbd" variant={"muted"}>
			Ctrl
		</Kbd>
```

2024-11-20 16:55 UTC, knowler commented on packages/kiwi-react/src/bricks/Kbd.css
> + *--------------------------------------------------------------------------------------------*/
Where is this coming from?
```suggestion
```

2024-11-20 16:55 UTC, knowler commented on packages/kiwi-react/src/bricks/Kbd.css
> +		color: #b8bdc1;
Is this colour not in the tokens? If it’s legitimately an exception, then we should still set it as a static custom property (i.e. as one prefixed with `--✨`).

2024-11-20 16:55 UTC, knowler commented on packages/kiwi-react/src/bricks/Kbd.css
> +		line-height: 16px; /* 133.333% */
We shouldn’t ever use `px` for `line-height`. Unitless is typically the best way to go (i.e. `1.33333`). Looking at iTwinUI, I notice it has `1` set and they use `padding-block` to set padding, I think that could be better.

2024-11-20 16:55 UTC, knowler commented on packages/kiwi-react/src/bricks/Kbd.css
> +		font-weight: 106;
Can you explain why `106`?

2024-11-20 16:55 UTC, knowler commented on packages/kiwi-react/src/bricks/Kbd.tsx
> +export const KbdKeys = {
I thin using an initial uppercase letter here gives the impression that this is a component when it’s not, especially when it’s being exported from a package that primarily consists of components. This should probably be `kbdKeys` instead.

2024-11-20 16:55 UTC, knowler commented on packages/kiwi-react/src/bricks/Kbd.css
> +		font-family: "Geist Mono";
Is this not set as a custom property? If not, it probably should be, at the theme-level.

2024-11-20 16:55 UTC, knowler commented on packages/kiwi-react/src/bricks/Kbd.css
> +		font-size: var(--size-12-body-small, 12px);
I don’t think we need the fallback and the fallback shouldn’t be in `px`.

2024-11-20 16:55 UTC, knowler commented on packages/kiwi-react/src/bricks/Kbd.css
> +		font-family: "Geist Mono";
Also, we probably need to add the font-face, because I’m getting the initial font (i.e. `serif`).

2024-11-20 16:55 UTC, knowler commented on packages/kiwi-react/src/bricks/Kbd.css
> +			font-weight: 84;
More magic values.

2024-11-20 16:55 UTC, knowler commented on packages/kiwi-react/src/bricks/Kbd.css
> +		padding: 0px 4px;
We should be using `padding-inline`. The `padding` shorthand uses physical directions.

2024-11-20 16:55 UTC, knowler commented on packages/kiwi-react/src/bricks/Kbd.css
> +		letter-spacing: 0px;
We shouldn’t need to set this.

```suggestion
```

2024-11-20 16:55 UTC, knowler commented on packages/kiwi-react/src/bricks/Kbd.tsx
> +);
This is using a `<div>` element, not the `<kbd>` element.

2024-11-20 16:55 UTC, knowler commented on packages/kiwi-react/src/bricks/Kbd.css
> +		height: 16px;
In general lets avoid both using `px` for `height` (which probably should be `block-size`), but also we shouldn’t need to set this here (i.e. use padding plus the height of the font to achieve the designed height).

2024-11-20 16:55 UTC, knowler commented on packages/kiwi-react/src/bricks/Kbd.css
> +		font-style: normal;
We don’t need this, this is the default.
```suggestion
```

2024-11-21 17:31 UTC, knowler commented on packages/kiwi-react/src/bricks/Kbd.css
> +		font-family: "Geist Mono";
Pending #152 merging:
```suggestion
		font-family: var(--kiwi-font-family-mono);
```

2024-11-25 10:31 UTC, RichardHill commented on packages/kiwi-react/src/bricks/Kbd.css
> +		font-weight: 106;
This was taken direct from Figma design. Is this something we should not set ? (ie ignore from the design ?). Looking elsewhere through the project I can see 400,500 and 600.

2024-11-25 10:39 UTC, RichardHill commented on packages/kiwi-react/src/bricks/Kbd.css
> + *--------------------------------------------------------------------------------------------*/
This was a working comment. When putting the CSS together I copied three version that I could see from figma and then removed duplicates as I worked on it for the 'solid' , 'muted' and 'ghost'.

2024-11-25 10:55 UTC, RichardHill commented on packages/kiwi-react/src/bricks/Kbd.css
> +		color: #b8bdc1;
I cannot find the colour in the project - (searched the files) This was taken directly from the design and I think its worth double checking this with the design team it seems an odd choice for a colour value.

2024-11-25 11:58 UTC, RichardHill commented on packages/kiwi-react/src/bricks/Kbd.css
> +		line-height: 16px; /* 133.333% */
Resolved : ddc897241856e799e6272ee00d380915124ee0d2

2024-11-25 12:10 UTC, RichardHill commented on packages/kiwi-react/src/bricks/Kbd.css
> +		padding: 0px 4px;
Resolved : c7c64dabde93d3a03b1b23f6d4a760b60a5f468f

2024-11-25 12:50 UTC, RichardHill commented on packages/kiwi-react/src/bricks/Kbd.tsx
> +);
Resolved : 0f87b968c970efc5382858d12f5df16eecce02f5

2024-11-25 13:01 UTC, RichardHill commented on packages/kiwi-react/src/bricks/Kbd.css
> +		height: 16px;
Is this a better approach ? :  40628fc6dbdd81ff0b88721d40c878904ccd31f9

2024-11-25 15:43 UTC, RichardHill commented on packages/kiwi-react/src/bricks/Kbd.css
> +		font-weight: 106;
This is now resolved : bbb085cb92b93d6f9e635e9913be470adf330550

After a conversation with the design team

2024-11-25 15:59 UTC, knowler commented on packages/kiwi-react/src/bricks/Kbd.css
> +		font-weight: 106;
Avoid using Figma’s CSS when we can. Instead reference the design tokens. In this case, I can see the typography for this component set to `weight/medium` [which typically maps to `500`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight#common_weight_name_mapping). In the future we’ll have custom properties for this.

2024-11-25 17:57 UTC, knowler commented on packages/kiwi-react/src/bricks/Kbd.tsx
> +);
We should still use Ariakit here, so let’s revert https://github.com/iTwin/kiwi/commit/0f87b968c970efc5382858d12f5df16eecce02f5 and instead we should just use a `render` prop on the `Ariakit.Role` component that renders a `<kbd>` element by default (but we still want the consumer to be able to override this with a `render` prop on our `<Kbd>` component).

2024-11-25 18:00 UTC, knowler commented on packages/kiwi-react/src/bricks/Kbd.css
> +		font-family: "Geist Mono";
Now that #152 is merged, we should rebase this.

2024-11-25 19:55 UTC, RichardHill commented on packages/kiwi-react/src/bricks/Kbd.css
> +		color: #b8bdc1;
This is now resolved : 02412f4a31f7c707e37cf0077ece6d41021ab506

2024-11-26 09:38 UTC, GerardasB commented on packages/kiwi-react/src/bricks/Kbd.tsx
> +interface KbdProps extends React.ComponentPropsWithoutRef<"kbd"> {
```suggestion
interface KbdProps extends Ariakit.RoleProps<"kbd"> {
```

To expose all of the Ariakit goodies?

2024-11-26 09:38 UTC, GerardasB commented on packages/kiwi-react/src/bricks/Kbd.tsx
> +	className?: string;
Comes with the base/extended prop type.
```suggestion
```

2024-11-26 09:38 UTC, GerardasB commented on packages/kiwi-react/src/bricks/Kbd.tsx
> +export const Kbd = forwardRef<HTMLElement, KbdProps>(
```suggestion
export const Kbd = forwardRef<React.ElementRef<"kbd">, KbdProps>(
```
nit: even if `kbd` element maps to `HTMLElement` interface, this makes it easier to understand w/o looking up the docs.

2024-11-26 09:38 UTC, GerardasB commented on apps/test-app/app/routes/tests/kbd/index.spec.tsx
> +	expect(kbdComponent).not.toBe(null);
This will never fail, i.e. no matter what test-id is passed in as arg as locator will always be created. I'd avoid using `testid` unless necessary as well:
```suggestion
	const kbd = page.getByText("Ctrl");
	await expect(kbd).toBeVisible();
```

2024-11-26 09:38 UTC, GerardasB commented on apps/test-app/app/routes/tests/kbd/index.spec.tsx
> +/*---------------------------------------------------------------------------------------------
Test file will never contain `jsx`, rename to `index.spec.ts`

2024-11-26 09:38 UTC, GerardasB commented on apps/test-app/app/routes/tests/kbd/index.spec.tsx
> +test("@visual", async ({ page }) => {
There are visual inconsistencies in generated snapshots (probably due to browser default styling). Or maybe it's just how fonts/emojis are rendered - are those discrepancies expected?

2024-11-26 09:38 UTC, GerardasB commented on apps/test-app/app/routes/tests/kbd/index.spec.tsx
> +	expect(isFocused).toBe(false);
```suggestion
	const kbd = page.getByText("Ctrl");
	await kbd.focus();

	await expect(kbd).not.toBeFocused();
```
Use playwright assertions instead.

2024-11-26 09:38 UTC, GerardasB commented on apps/test-app/app/routes/tests/kbd/index.tsx
> +		<Kbd data-testid="kbd" variant={"muted"}>
```suggestion
		<Kbd variant="muted">
```
We can use `getByText` instead.

2024-11-26 12:50 UTC, RichardHill commented on packages/kiwi-react/src/bricks/Kbd.tsx
> +interface KbdProps extends React.ComponentPropsWithoutRef<"kbd"> {
Good thought. I went with my approach as screen readers seem to ignore kbd - but thats now - what about future? Your idea here would future proof this. Thanks.

2024-11-26 14:03 UTC, RichardHill commented on apps/test-app/app/routes/tests/kbd/index.tsx
> +		<Kbd data-testid="kbd" variant={"muted"}>
nice tip - thanks.

2024-11-26 14:20 UTC, RichardHill commented on apps/test-app/app/routes/tests/kbd/index.tsx
> +		<Kbd data-testid="kbd" variant={"muted"}>
Resolved : 83509da83f0d0cb4eaac03f54e16a77b7cd5d1bf

2024-11-26 15:27 UTC, RichardHill commented on apps/test-app/app/routes/tests/kbd/index.spec.tsx
> +/*---------------------------------------------------------------------------------------------
Resolved : e6ee7d5fe5b263c8374a29f6ab2445fba614e57c

2024-11-26 15:28 UTC, RichardHill commented on apps/test-app/app/routes/tests/kbd/index.spec.tsx
> +	expect(kbdComponent).not.toBe(null);
Resolved : c81d4e133baa3b0e538e92a1aa25abc2da5ecb52

2024-11-26 17:47 UTC, knowler commented on packages/kiwi-react/src/bricks/Kbd.css
> +		line-height: 16px; /* 133.333% */
I think I’d prefer to use `line-height: 1` like iTwinUI, so let’s do that and accomplish the rest of the spec’d `block-size` with `padding-block`.

2024-11-26 17:53 UTC, mayank99 commented on packages/kiwi-react/src/bricks/Kbd.css
> +		line-height: 16px; /* 133.333% */
Do we need to set `133%` at the global level, and maybe we shouldn't even set it in Kbd?

2024-11-26 18:07 UTC, mayank99 commented on packages/kiwi-react/src/bricks/Kbd.tsx
> +export const KbdKeys = {
I think we can exclude `KbdKeys` from the initial implementation. We should take the time to come up with a proper curated list in the future, rather than just copying what's in iTwinUI.

2024-11-26 18:42 UTC, RichardHill commented on packages/kiwi-react/src/bricks/Kbd.tsx
> +export const KbdKeys = {
This list is different from iTwinUI. It uses some of the items there - but also I did some research into what might be considered the most useful or used keys.

2024-11-26 19:25 UTC, mayank99 commented on packages/kiwi-react/src/bricks/Kbd.tsx
> +export const KbdKeys = {
Could you please share your research and initiate a discussion when making important decisions like this? Anything that's in the library needs to be carefully considered, because we can't easily remove it once added.

In any case, the initial task was just to add `<Kbd>`, which is a standalone piece. The `KbdKeys` discussion can be had separately and shouldn't block this PR.

2024-11-26 20:22 UTC, GerardasB commented on apps/test-app/app/routes/tests/kbd/index.spec.tsx
> +	expect(kbdComponent).not.toBe(null);
`expect(kbdComponent).not.toBe(null);` is still there, make sure to replace to `await expect(kbdComponent).toBeVisible();` (otherwise it only checks if the locator object is created). Btw, you can simply use `Commit suggestion` button from GitHub UI.

2024-11-26 21:19 UTC, RichardHill commented on packages/kiwi-react/src/bricks/Kbd.tsx
> +export const KbdKeys = {
Resolved: d0287576c803ad3b96b5a5ae548b3b17b599e34f

I used some research links from bookmarks as follows :  [(1)](https://flowbite.com/docs/components/kbd/), [(2)](https://nextui.org/docs/components/kbd).

2024-11-26 21:24 UTC, RichardHill commented on apps/test-app/app/routes/tests/kbd/index.spec.tsx
> +	expect(kbdComponent).not.toBe(null);
Please see this commit : 6e4a7dae8385a8e2a9b344016b66f170237ac48b

(thats odd - this commit has that in. Commit suggestion is greyed out for me )

2024-11-26 21:38 UTC, RichardHill commented on packages/kiwi-react/src/bricks/Kbd.tsx
> +);
Good call about wanting to provide their own representation/presentation. Something like this ? 222e44a003e5e6878c2141495dd71407b40c4091

2024-11-26 22:05 UTC, RichardHill commented on packages/kiwi-react/src/bricks/Kbd.css
> +		line-height: 16px; /* 133.333% */
@knowler - line-height resolved here : 6878d0d7b5999b5438c9516b88d9e4d61002165d

2024-11-26 22:07 UTC, knowler commented on packages/kiwi-react/src/bricks/Kbd.tsx
> +);
Yes, that’s the direction, but instead of spreading props onto the `<kbd>` element, you can just set it like `render={render || <kbd />}` since we’re not modifying those props.

2024-11-26 22:21 UTC, RichardHill commented on packages/kiwi-react/src/bricks/Kbd.tsx
> +);
Removed Prop Spread : d1c26defc8194057b03f24953c551865a828f4f6

2024-11-26 23:01 UTC, RichardHill commented on packages/kiwi-react/src/bricks/Kbd.tsx
> +export const Kbd = forwardRef<HTMLElement, KbdProps>(
Commit : cfa0491033cc23c88fb1de1fd616506fc6f1d681

I got this to work by casting the ref as below 

```ts
export const Kbd = React.forwardRef<React.ElementRef<"kbd">, KbdProps>(
	({ variant = "solid", className, children, render, ...rest }, ref) => {
		return (
			<Ariakit.Role
				ref={ref as React.Ref<HTMLDivElement>}
				data-kiwi-variant={variant}
				className={cx("🥝-kbd", className)}
				render={render || <kbd />}
				{...rest}
			>
				{children}
			</Ariakit.Role>
		);
	},
);
```

Does this detract from the understanding you were after ?

2024-11-26 23:05 UTC, RichardHill commented on packages/kiwi-react/src/bricks/Kbd.css
> +		line-height: 16px; /* 133.333% */
> Do we need to set `133%` at the global level, and maybe we shouldn't even set it in Kbd?

Button, ListItem and Kbd use similar values for line-height - does that repetition qualify for global setting?

2024-11-27 14:50 UTC, GerardasB commented on packages/kiwi-react/src/bricks/Kbd.tsx
> +export const Kbd = forwardRef<HTMLElement, KbdProps>(
I think this is fine, alternatively you could cast to `Ariakit.RoleProps["ref"]`

2024-11-27 17:25 UTC, RichardHill commented on apps/test-app/app/routes/tests/kbd/index.spec.tsx
> +test("@visual", async ({ page }) => {
Reviewed and agreed to update images : c3bd974f2ee47c273d5d4645bbacf345c8a19828

2024-11-27 17:32 UTC, RichardHill commented on packages/kiwi-react/src/bricks/Kbd.css
> +		line-height: 16px; /* 133.333% */
Agreed to go with a global value for this and remove it from the component. d8b9e66dd0b5748e4a93a61ff90383ed49eb70df

2024-11-27 18:23 UTC, mayank99 commented on packages/kiwi-react/src/bricks/Kbd.tsx
> + * <Kbd>Ctrl</Kbd>
The JSDoc comment can be made more useful.

```suggestion
 * A styled wrapper over the HTML `<kbd>` element. This is typically
 * used for displaying keyboard shortcuts.
 *
 * ```tsx
 * <Kbd>Ctrl</Kbd> <Kbd>S</Kbd>
 * ```
```

2024-11-27 18:23 UTC, mayank99 commented on packages/kiwi-react/src/bricks/Kbd.tsx
> +);
This can be reorganized to follow the same conventions used in the rest of the codebase.

```suggestion
export const Kbd = React.forwardRef<React.ElementRef<"kbd">, KbdProps>(
	(props, forwardedRef) => {
		const { variant = "solid", ...rest } = props;
		return (
			<Ariakit.Role
				data-kiwi-variant={variant}
				{...rest}
				className={cx("🥝-kbd", props.className)}
				render={props.render || <kbd />}
				ref={forwardedRef as Ariakit.RoleProps["ref"]}
			/>
		);
	},
);
```

2024-11-27 18:23 UTC, mayank99 commented on apps/test-app/app/routes/tests/kbd/index.spec.ts
> +	const kbdComponent = page.getByText("Ctrl");
We should validate that this is actually rendering a `<kbd>` element. This can be done by checking the element's [`localName`](https://developer.mozilla.org/en-US/docs/Web/API/Element/localName).

```suggestion
	const kbdComponent = page.getByText("Ctrl");
	expect(await kbdComponent.evaluate((e) => e.localName)).toBe("kbd");
```

2024-11-27 18:23 UTC, mayank99 commented on apps/test-app/app/routes/tests/kbd/index.spec.ts
> +});
I'm not sure that this focusable test is necessary.

2024-11-27 18:23 UTC, mayank99 commented on packages/kiwi-react/src/bricks/Kbd.css
> +		text-align: center;
This looks redundant/unnecessary.

```suggestion
```

2024-11-27 18:23 UTC, mayank99 commented on packages/kiwi-react/src/bricks/Kbd.css
> +			padding-inline: 0px;
Instead of setting padding and then removing it from the ghost variant, we can only set it for the solid and muted variants.

2024-11-27 18:23 UTC, mayank99 commented on packages/kiwi-react/src/bricks/Kbd.css
> +		padding-block: 4px;
The Figma design doesn't have any `padding-block`. Instead it sets a fixed height of `16px` for all variants. We should do the same but using `min-block-size`.

2024-11-27 18:23 UTC, mayank99 commented on packages/kiwi-react/src/bricks/Kbd.css
> +			background: #36393f;
These colors need to use our tokens instead of hex values.

2024-11-28 11:24 UTC, RichardHill commented on apps/test-app/app/routes/tests/kbd/index.spec.ts
> +});
Removed: f9925b720c89120a27141e2bad4ae14294e429bf . My motivation was to give test coverage. By default this element does not receive focus unless, for example the tabindex is set.

2024-11-28 11:39 UTC, RichardHill commented on packages/kiwi-react/src/bricks/Kbd.css
> +			padding-inline: 0px;
Resovled : a48da65e7a56e7c3f5cf87cf710af05288ac4b24

2024-11-28 12:00 UTC, RichardHill commented on packages/kiwi-react/src/bricks/Kbd.css
> +			background: #36393f;
Tokens added : f0eb7aa2f0865f240156149140e80c88f298b3e6

2024-11-28 12:10 UTC, RichardHill commented on packages/kiwi-react/src/bricks/Kbd.css
> +		font-style: normal;
This is resolved.

2024-11-28 12:23 UTC, GerardasB approved these changes

2024-11-28 12:23 UTC, GerardasB commented on apps/test-app/app/routes/tests/kbd/index.spec.ts
> +test("@visual", async ({ page }) => {
There should be only 3 snap files (not 6, this is due to test file rename).

2024-11-28 13:43 UTC, RichardHill commented on packages/kiwi-react/src/bricks/Kbd.tsx
> +export const KbdKeys = {
These have now been removed from a previous comment asking that they should be discussed in more detail outside of this PR.

2024-11-28 13:48 UTC, RichardHill commented on packages/kiwi-react/src/bricks/Kbd.css
> +		font-weight: 106;
That a V useful link on the 500 - thanks for sharing @knowler

2024-11-28 14:24 UTC, RichardHill commented on packages/kiwi-react/src/bricks/Kbd.css
> +		padding-block: 4px;
Resolved here : 10be7b1ecb71813aeb45f5a091d372b1b8f46ef4

(nb: I was taking direction from [here](https://github.com/iTwin/kiwi/pull/139#discussion_r1850628392) )

2024-11-28 14:30 UTC, RichardHill commented on apps/test-app/app/routes/tests/kbd/index.spec.ts
> +test("@visual", async ({ page }) => {
Resolved : 52342b9602df32c3949ee90918ffa1f80bc58dd7

2024-11-28 14:55 UTC, mayank99 commented on packages/kiwi-react/src/bricks/Kbd.css
> +			background: #36393f;
Also nit: we should use `background-color` instead of the `background` shorthand (which sets `background-color`, `background-image` and a few other properties)

2024-11-28 14:56 UTC, mayank99 commented on packages/kiwi-react/src/bricks/Kbd.css
> +		padding-block: 4px;
@knowler Can you look at this and share your thoughts? I think `px` might be ok here, because we are setting `min-block-size`, not `block-size`.

The main point of this comment is to match the Figma visuals, which it wasn't doing when we were setting `padding-block` instead of `min-block-size`.

2024-11-28 14:59 UTC, mayank99 commented on packages/kiwi-react/src/bricks/Kbd.css
> +			font-weight: 84;
This was mentioned [earlier](https://github.com/iTwin/kiwi/pull/139#discussion_r1850648175). I don't know where it's coming from, but it needs to be removed.

2024-11-28 15:40 UTC, RichardHill commented on packages/kiwi-react/src/bricks/Kbd.css
> +			font-weight: 84;
Resolved: 8ef1c3e352eb79ea4852909bf306686e9237bedd

2024-11-28 15:42 UTC, RichardHill commented on packages/kiwi-react/src/bricks/Kbd.css
> +			background: #36393f;
Resolved: 13cdbcdf22d32261b880f4619e60282649b5ffa7

2024-11-28 16:07 UTC, mayank99 approved these changes
LGTM, but I would wait for @knowler's response in the [unresolved thread](https://github.com/iTwin/kiwi/pull/139#discussion_r1862341877) before merging.

2024-11-28 16:32 UTC, knowler commented on packages/kiwi-react/src/bricks/Kbd.css
> +		padding-block: 4px;
I definitely like the idea of `min-block-size` more than `block-size` or `height`. I tend to use `padding-block` in designs because design tools typically don’t encourage thinking about what happens when the user has scaled the text and so I usually infer padding as the intent of the designer even though they might be accomplishing it with a fixed height or even `line-height`. In this case, I don’t think it makes a difference (at least from my testing), so **I’m fine with using `min-block-size`**.

- - -

With that said, since we’re not setting `line-height` any more, I think we should ask ourselves what we want to see in situations where we aren’t inherited the global `line-height` (i.e. 1.3333) — do we want the box to match the line-height of the surrounding content? Or do we want it to remain `1.3333`, in which case we should hard-code it at the component-level? I personally think the latter looks better and so **I think we should hardcode `line-height: 1.3333` as well**.

<p><figure><figcaption>Example: inheriting from a parent with <code>line-height: 2</code></figcaption><img width="538" alt="The Kbd component used at the end of a paragraph of Lorem. The paragraph’s line-height is 2 and since its inheriting the Kbd component matches it which means it’s visually taller." src="https://github.com/user-attachments/assets/4e9fa2f0-cc4f-47dc-8067-6f8b61ff4311"></figure></p>

<p><figure><figcaption>Example: hardcoded as <code>line-height: 1.3333</code></figcaption><img width="538" alt="image" src="https://github.com/user-attachments/assets/12a324ab-f27a-479e-9f95-33cfcb17f6d2"></figure></p>

And I know that might seem counter to a previous recommendation I made, but I don’t think those were fully understood (i.e. I was suggesting a combination of using `line-height: 1` like iTwinUI does instead of `line-height: 1.3333`, then using `padding-block` to make up the rest of the height, but instead `line-height` was completely removed in favour of inheriting).

2024-11-28 16:44 UTC, mayank99 commented on packages/kiwi-react/src/bricks/Kbd.css
> +		padding-block: 4px;
That explanation makes sense to me, and I'm fine with adding `line-height: 1.3333` here 👍

2024-11-28 16:48 UTC, RichardHill commented on packages/kiwi-react/src/bricks/Kbd.css
> +		padding-block: 4px;
I prefer the look of component level (1.333) - not inheriting. It looks 'tighter'. The inherited option looks 'baggy' to me. ( weird use of vocab I know but thats what springs to mind )

2024-11-28 16:49 UTC, RichardHill commented on packages/kiwi-react/src/bricks/Kbd.css
> +		padding-block: 4px;
Should we review this with designers?

2024-11-28 17:18 UTC, RichardHill commented on packages/kiwi-react/src/bricks/Kbd.css
> +		padding-block: 4px;
Resolved : 73fb761fdf6c3e5c07f893bb1cfda92e457307e2

2024-11-28 18:05 UTC, knowler approved these changes
Nice. Thanks for handling all of that feedback.

2024-11-28 18:18 UTC, merged