Styles for the Tooltip
iTwin/stratakit pull request #81
Opened 2024-10-10 21:52 UTC by RichardHill

**Summary**

This PR introduces Figma-defined styling for the Kiwi Tooltip component, following the design specifications outlined in the Figma file. 

![image](https://github.com/user-attachments/assets/f094d3f8-32f3-4c27-b224-a0d0993e68e9)

Where applicable, CSS variables have been defined and utilized in accordance with the existing Kiwi variable naming conventions for flexibility and consistency.

An image of the Tooltip with single line content :

![image](https://github.com/user-attachments/assets/277265bc-68b7-451d-b16b-20427248626e)

An image of the Tooltip with multiple line content :

![image](https://github.com/user-attachments/assets/cf84c9e6-d85f-4d22-a0f1-1db853612bdb)

**Changes**

Applied Figma-based design tokens to the tooltip's base layer.
Defined and integrated reusable variables for padding, border radius, box-shadow, and color to ensure maintainability and theme compatibility.

**Notes**

The base layer of the tooltip has been fully implemented.
No state-specific styles (e.g., hover, focus, or active states) are defined in this PR. These will be addressed in a future update if necessary.

2024-10-16 20:35 UTC, knowler commented on packages/kiwi-react/src/bricks/Tooltip.css
> +		--_kiwi-tooltip-padding-horizontal: 0.25rem;
I think we should avoid the use of the terms `horizontal` and `vertical` in custom property names (and use logical names instead, e.g. `inline` and `block` as well as `start` and `end` when relevant). I also want to verify if this really needs to be a custom property, since it’s only being used once and not even for both ends of its axis.

2024-10-16 20:44 UTC, knowler commented on packages/kiwi-react/src/bricks/Tooltip.css
> +		--_kiwi-tooltip-padding-horizontal: 0.25rem;
For some reason I’m not even seeing the styles in the CI preview. It looks like they are added correctly though. 🤔

2024-10-16 21:00 UTC, knowler requested changes
I’ve requested some changes. From reviewing the linked design, I believe we need some padding on the block-axis as well. I’m not sure we really need all of the custom properties as a number of them are internal and aren’t being used more than once.

2024-10-16 21:00 UTC, knowler commented on packages/kiwi-react/src/bricks/Tooltip.css
> +		padding-inline-start: var(--_kiwi-tooltip-padding-horizontal);
There should be equal padding on each end of the inline-axis.
```suggestion
		padding-inline: 0.25rem;
```

2024-10-16 21:00 UTC, knowler commented on packages/kiwi-react/src/bricks/Tooltip.css
> +		--_kiwi-tooltip-padding-horizontal: 0.25rem;
Lets get rid of the custom property.
```suggestion
```

2024-10-16 21:00 UTC, knowler commented on packages/kiwi-react/src/bricks/Tooltip.css
> +		min-height: 16px;
Let’s avoid `px` when we can:
```suggestion
		min-height: 1rem;
```

2024-10-16 22:32 UTC, mayank99 requested changes
I agree with @knowler that most (all?) of the custom properties are unnecessary. `--_kiwi-tooltip-color-box-shadow` in particular is a no-go, because we expect the entire shadows to be part of our semantic tokens.

The visuals also look off (the text is not centered), which I'm not sure is intentional. A screenshot in PR description would help verify whether we're seeing the same thing. And of course, we need visual tests.

---

To @knowler's other point, I agree inline padding should be symmetrical. I'm not sure that we need block padding though (there is none in Figma; although we still need to vertically center the content).

^This is something we need to confirm with designers. I'm also interested in finding out what happens when there is a lot of text. That's a case where block padding + max inline size would both come in handy.

2024-10-18 10:18 UTC, RichardHill commented on packages/kiwi-react/src/bricks/Tooltip.css
> +		--_kiwi-tooltip-padding-horizontal: 0.25rem;
Agree. I need to stop thinking into the future where I 'think' something might be useful and just accept what is here and now ! :)

2024-10-18 10:46 UTC, RichardHill commented on packages/kiwi-react/src/bricks/Tooltip.css
> +		--_kiwi-tooltip-padding-horizontal: 0.25rem;
Given this has changed in the design - please accept that I am not going to commit this change :)

2024-10-21 14:25 UTC, mayank99 commented on packages/kiwi-react/src/bricks/Tooltip.css
> +		box-shadow: 0px 1px 1px -0.5px #00000029, /* Layer 1 */ 0px 3px 3px -1.5px #00000029, /* Layer 2 */
The comments can be removed from these shadows.

2024-10-21 14:25 UTC, mayank99 commented on packages/kiwi-react/src/bricks/Tooltip.css
> +		line-height: 1rem;
I don't think we need to set line-height here?

2024-10-21 14:25 UTC, mayank99 commented on packages/kiwi-react/src/bricks/Tooltip.css
> +		min-height: 1rem;
We should use logical properties where possible.
```suggestion
		min-block-size: 1rem;
```

2024-10-21 14:25 UTC, mayank99 commented on packages/kiwi-react/src/bricks/Tooltip.css
> +		padding: 0.125rem 0.25rem;
We should use logical properties where possible.

```suggestion
		padding-block: 0.125rem;
		padding-inline: 0.25rem;
```

2024-10-21 14:25 UTC, mayank99 commented on packages/kiwi-react/src/bricks/Tooltip.css
> +		font-size: 0.75rem;
The order and grouping of CSS declarations in this file feels unorganized. `font-size` should be near the top, and `justify-content` should be grouped with `display: flex`. The extra newlines should be used intentionally.

2024-10-21 14:25 UTC, mayank99 commented on packages/kiwi-react/src/bricks/Tooltip.css
> +		padding: 0.125rem 0.25rem;
Currently missing: the extra padding when tooltip text wraps into multiple lines.

2024-10-21 14:25 UTC, mayank99 commented on apps/test-app/app/routes/tests/tooltip/index.tsx
> +	const checked = searchParams.get("multi-line") === "true";
The `checked` variable name looks wrong.

2024-10-21 14:25 UTC, mayank99 commented on apps/test-app/app/routes/tests/tooltip/index.spec.ts-snapshot.-visual-tooltip-content-with-multiple-lines-1-webkit-darwin.png
The `darwin` test images need to be removed. These are from your local machine (outside Docker).

2024-10-21 14:25 UTC, mayank99 commented on apps/test-app/app/routes/tests/tooltip/index.spec.ts
> +	});
I'm not sure that this `beforeEach` block does anything, since all the code is repeated in both visual tests.

2024-10-21 15:35 UTC, knowler commented on packages/kiwi-react/src/bricks/Tooltip.css
> +		line-height: 1rem;
Also, as a general note it almost always should be unitless. So, this case to maintain the current line-height that’s set 1rem (`line-height`) / 0.75rem (`font-size`) is 1.333333… — but like Mayank said, we’ll need to check with the default to confirm this is necessary.

2024-10-21 15:51 UTC, knowler commented on packages/kiwi-react/src/bricks/styles.css
> +@import "./Radio.css" layer(kiwi.components);
Just curious why the Radio import is changing in this PR? If it doesn’t need to, let’s revert this.

2024-10-22 09:54 UTC, RichardHill commented on packages/kiwi-react/src/bricks/Tooltip.css
> +		box-shadow: 0px 1px 1px -0.5px #00000029, /* Layer 1 */ 0px 3px 3px -1.5px #00000029, /* Layer 2 */
I actually thought this was useful, hence them being here. They give a useful visual cue to what is otherwise just a bunch of numbers you have to break up visually without the comments being there.

Removed here : 2f49b3d6cc7fa20a4cc16c1fd712e75c14ae6bb7

2024-10-22 09:58 UTC, RichardHill commented on packages/kiwi-react/src/bricks/Tooltip.css
> +		line-height: 1rem;
Ah ok - so by not specifying a unit the line-height will be calculated as a factor of the elements font-size, ok.

2024-10-22 10:07 UTC, RichardHill commented on packages/kiwi-react/src/bricks/Tooltip.css
> +		line-height: 1rem;
This differs from the design that Matt has in place and after a conversation with him regarding his visual feedback.

![image](https://github.com/user-attachments/assets/1670813f-8df6-4033-ac08-e41fddc3fb95)

Removed in this commit : 6a44cc554474d85e8c89a1c1c25171d3c353588a

2024-10-22 10:10 UTC, RichardHill commented on packages/kiwi-react/src/bricks/Tooltip.css
> +		min-height: 1rem;
Ok - in that case I am changing the padding to this -: . 

```css
padding-block: 0.125rem; 
padding-inline: 0.25rem;
```

2024-10-22 10:10 UTC, RichardHill commented on packages/kiwi-react/src/bricks/Tooltip.css
> +		min-height: 1rem;
Just seen comment below!

2024-10-22 10:22 UTC, RichardHill commented on packages/kiwi-react/src/bricks/Tooltip.css
> +		font-size: 0.75rem;
This is address in this commit : ae6401a821c1e58dd6abe9b116f1d42744600b44

2024-10-22 10:31 UTC, RichardHill commented on apps/test-app/app/routes/tests/tooltip/index.tsx
> +	const checked = searchParams.get("multi-line") === "true";
Good call. Resolved here : 6818cb04dec8b54d0fce8b291944292f8d5c55f9

2024-10-22 10:32 UTC, RichardHill commented on apps/test-app/app/routes/tests/tooltip/index.spec.ts-snapshot.-visual-tooltip-content-with-multiple-lines-1-webkit-darwin.png
Resolved here : 3d26b9fe68bdb0f6519d3e9f19e76051a08b76b8

2024-10-22 10:46 UTC, RichardHill commented on apps/test-app/app/routes/tests/tooltip/index.spec.ts
> +	});
Agreed. It feels like duplicity. Removed and tests seem stable.

Commit here : ebd866fc798e88b9179e6df2e0bce2f4eee563c3

2024-10-22 10:51 UTC, RichardHill commented on packages/kiwi-react/src/bricks/styles.css
> +@import "./Radio.css" layer(kiwi.components);
It was to put it into alphabetical order.

Resolved here : 1580118b70b9a071a27d5ec15dcafd7bc676a513

2024-10-22 16:26 UTC, RichardHill commented on packages/kiwi-react/src/bricks/Tooltip.css
> +		padding: 0.125rem 0.25rem;
@mayank99 I've been looking into this. 

You kindly shared that a solution here would be to use [container queries](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_containment/Container_queries) .

To implement this, the CSS and mark up needs some changes.

Firstly for the query to fire its necessary to implement '[container-type](https://developer.mozilla.org/en-US/docs/Web/CSS/container-type)'. This needs to be applied to the parent element. In the JSX below I have done this by introducing a containing 'div' with the "🥝-tooltip-container" class applied.

This is the CSS for that class :

```css
.🥝-tooltip-container {
	container-type: inline-size; /* Enable container queries based on width */
}
```

Then in the JSX we have : 

```jsx
<>
	<Ariakit.TooltipProvider>
		<Ariakit.TooltipAnchor render={children} aria-describedby={id} />
		<div className="🥝-tooltip-container">
			<Ariakit.Tooltip
				{...rest}
				className={cx("🥝-tooltip", className)}
				ref={forwardedRef}
				id={id}
			>
				{content}
			</Ariakit.Tooltip>
		</div>
	</Ariakit.TooltipProvider>
</>
```

Finally the query : 

```css
/* Container query to adjust padding when the tooltip exceeds 12.25rem */
@container (min-width: 1.25rem) {
	.🥝-tooltip {
		background-color: red;
		padding-block: 0.25rem; /* Increase the padding when the tooltip is wider */
		padding-inline: 0.5rem;
	}
}

```

This doesn't work because the JSX for the ARIA Tooltip doesn't render into a nice parent child format. This is to work around any issues of being over-laid.   It doesn't.  You can turn this off with the portal property.

```jsx
portal={false}
```


![image](https://github.com/user-attachments/assets/a1e834dc-6f51-4646-aadf-b10af1c0ec67)

Documented [here](https://ariakit.org/reference/tooltip).  

If we change the JSX to include 'portal' and set it to false. The container query starts firing. However the sizing is all out. For example the max-inline-size is set at 12.25rem however I cannot ever get it to fire properly at a size that we are interested in. 

I've spent a few hours on this now and I think what I have commited here : 8cb07d926f967264a150c3e85bd54d915b54054a

Is starting to get close - but it just doesn't seem to behave and the portal=false concerns me....

2024-10-22 19:11 UTC, mayank99 commented on packages/kiwi-react/src/bricks/Tooltip.css
> +		box-shadow: 0px 1px 1px -0.5px #00000029, /* Layer 1 */ 0px 3px 3px -1.5px #00000029, /* Layer 2 */
I agree, the comments can help with readability, even though I found the placement of these comments misleading (e.g. `/* Layer 1 */` is placed after the comma, making it part of the second layer).

However, the main reason I'm asking to remove the comments is that we will be replacing the entire shadow value with a variable in the near future. So this declaration would become something like `box-shadow: var(--kiwi-shadow-base)`.

2024-10-22 19:13 UTC, mayank99 commented on packages/kiwi-react/src/bricks/Tooltip.css
> +		line-height: 1rem;
Do we need to have another conversation with Matt? It would be good to clarify the intent of the design. I know that line-height differs significantly in Figma, because it has different leading (which can even be trimmed! something that CSS doesn't currently offer)

**Edit**: It was clarified during a conversation with designers that tooltip is not meant to have a bespoke line-height.

2024-10-22 19:45 UTC, mayank99 commented on packages/kiwi-react/src/bricks/Tooltip.css
> +		padding: 0.125rem 0.25rem;
You are right, it needs a container; that's a requirement to prevent "layout loops". I would have expected this container to be part of the tooltip itself, rather than being outside the tooltip. That way we wouldn't need to change any portaling behavior. (`portal={false}` is undesirable)

<details><summary>Code</summary>

```jsx
<Ariakit.Tooltip
	{...rest}
	className={cx("🥝-tooltip-container", className)}
	ref={forwardedRef}
	id={id}
>
	<div className="🥝-tooltip">{content}</div>
</Ariakit.Tooltip>
```

</details> 

However, this still doesn't get us where we want to be. As you've noticed, the container collapses to be zero width. This is one of the requirements/limitations of container queries, again to prevent "layout loops". Containers cannot be sized intrinsically by their content; they need to be sized explicitly. Which of course doesn't help us, since we very much want to change the padding based on the size of the content.

So unfortunately, I think we cannot use container queries for this scenario. 🙁

The other route would be using JS to measure the size, but that very much seems overkill for adjusting the padding by a few pixels. Another option I thought about was counting the number of characters in the `content` prop, but its value may not always be a string, which makes it unreliable.

Unless we can find some clever CSS solution (/cc @knowler), I think we need to discuss this with Matt again. It would be so much simpler to just use the same padding for all cases. This is a problem for designers too — are we expecting consumers of the Figma library to manually toggle the Tooltip padding using some prop when the content is long?

2024-10-23 12:58 UTC, RichardHill commented on packages/kiwi-react/src/bricks/Tooltip.css
> +		padding: 0.125rem 0.25rem;
<rant> Here we are in 2024 and dealing with what I think are simple issues with styling that CSS STILL cannot help use achieve. I 'get' that this is a niche - but really its quite simple - we want a CSS approach that will fire under a given set of circumstances - containers are SO close but yet the reliance on the container and its inherent behaviour means it will not work. There has been suffice time for the standards to adopt and improve to cater for these sorts of situations.</rant>

:)

To be clear I'm not upset just annoyed, really.

2024-10-23 20:45 UTC, mayank99 commented on packages/kiwi-react/src/bricks/Tooltip.css
> +		padding: 0.125rem 0.25rem;
After today's conversation with designers, it was decided that we want the following padding values (unconditional):

```css
padding-block: 0.25rem;
padding-inline: 0.5rem;
```

2024-10-24 07:38 UTC, GerardasB commented on packages/kiwi-react/src/bricks/Tooltip.tsx
> +						portal={false}
Disabling the portalling like that seems very limiting, do we still need that?

2024-10-24 09:04 UTC, RichardHill commented on packages/kiwi-react/src/bricks/Tooltip.tsx
> +						portal={false}
@GerardasB - to explain - I shared this as WIP and to stimulate conversation around the problems with getting the container queries to work. I strongly suspect this will be reverted.

2024-10-24 10:53 UTC, RichardHill commented on packages/kiwi-react/src/bricks/Tooltip.css
> +		padding: 0.125rem 0.25rem;
Resolved here : 717e23f0b431568190354a77a57b94c448fde829

2024-10-24 10:55 UTC, RichardHill commented on packages/kiwi-react/src/bricks/Tooltip.tsx
> +						portal={false}
Now reverted here : 717e23f0b431568190354a77a57b94c448fde829

2024-10-24 16:19 UTC, mayank99 commented on apps/test-app/app/routes/tests/tooltip/index.tsx
> +		undefined;
This is redeclared below, causing the build to fail.

```suggestion
```

2024-10-24 16:19 UTC, mayank99 commented on packages/kiwi-react/src/bricks/Tooltip.css
> +		min-height: 1rem;
[This change](https://github.com/iTwin/kiwi/pull/81/files#r1808921566) still needs to be made.

2024-10-24 16:19 UTC, mayank99 commented on packages/kiwi-react/src/bricks/Tooltip.css
> +		gap: 0.125rem;
While it's not super relevant for the "text-only" tooltip, I believe the design was updated to use a larger gap.

```suggestion
		gap: 0.25rem;
```

2024-10-24 16:40 UTC, RichardHill commented on apps/test-app/app/routes/tests/tooltip/index.tsx
> +		undefined;
Yep - just resolving.

2024-10-24 16:40 UTC, RichardHill commented on apps/test-app/app/routes/tests/tooltip/index.tsx
> +		undefined;
Here : c11485f66d990e157173c4c929d6c5ab607c84d8

2024-10-24 16:46 UTC, knowler approved these changes

2024-10-24 17:04 UTC, mayank99 approved these changes
LGTM 🚀

2024-10-24 17:09 UTC, merged